### ISSUE TITLE
Peer interview: Colleen Theisen

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/RecipeCrowdsourcingTasks#1]

**Comment by mialondon** [comment]
Some follow-up questions - do they track referrers to know whether they lead to contributions? e.g. do Reddit users read then leave, or do some transcribe?

Do they have thoughts on motivating people to complete reviewing transcriptions?

Is there an example of an OCR correction project that hasn't attracted contributors?

**Comment by mialondon** [comment]
It'd be good to talk to Special Collections, too, to see whether their goals are substantially different.
