### ISSUE TITLE
Install & Evaluate DIYHistory

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/RecipeCrowdsourcingTasks#11]

**Comment by mialondon** [comment]
Do you want me to have a go if you haven't already?

**Comment by benwbrum** [comment]
Honestly, I feel like I already know enough about it for the paper after
the interview with Matt Butler.  Ditto for Mirador and Shaun Ellis.  If
you'd like to give it a go, it certainly can't hurt, though!

Ben

**Comment by mialondon** [comment]
I'll see how I go for time then - fingers crossed we won't need another trip to London before I go to Estonia!
