### ISSUE TITLE
Are Panoptes outputs compatible with ALTO?

### ISSUE THREAD

**Issue by mialondon** [benwbrum/RecipeCrowdsourcingTasks#6]
If not, what systems are they designed for?

**Comment by benwbrum** [comment]
They actually look a lot like the outputs from NotesFromNature I worked with a few yaers ago.

I suspect that post-processing will be necessary to make them compatible with ALTO, if that ends up being desirable.

**Comment by mialondon** [comment]
It might well be, as yesterday it came up quite a bit and has some use in internal systems.
